import 'package:amui_digital_event_app/models/event_model.dart';

List<EventModel> eventDummyList = [
  EventModel(
      id: "dsdd",
      name: 'Electrical Conference',
      description: 'More details will be available on the given url website',
      url: "https://facebook.com",
      department: 'Electrical',
      faculty: 'Engineering',
      startDate: DateTime.now(),
      endDate: DateTime.now(),
      online: true),EventModel(
      id: "dsdd",
      name: 'Electrical Conference',
      description: 'More details will be available on the given url website',
      url: "https://facebook.com",
      department: 'Electrical',
      faculty: 'Engineering',
      startDate: DateTime.now(),
      endDate: DateTime.now(),
      online: true),EventModel(
      id: "dsdd",
      name: 'Electrical Conference',
      description: 'More details will be available on the given url website',
      url: "https://facebook.com",
      department: 'Electrical',
      faculty: 'Engineering',
      startDate: DateTime.now(),
      endDate: DateTime.now(),
      online: true),EventModel(
      id: "dsdd",
      name: 'Electrical Conference',
      description: 'More details will be available on the given url website',
      url: "https://facebook.com",
      department: 'Electrical',
      faculty: 'Engineering',
      startDate: DateTime.now(),
      endDate: DateTime.now(),
      online: true),EventModel(
      id: "dsdd",
      name: 'Electrical Conference',
      description: 'More details will be available on the given url website',
      url: "https://facebook.com",
      department: 'Electrical',
      faculty: 'Engineering',
      startDate: DateTime.now(),
      endDate: DateTime.now(),
      online: true),EventModel(
      id: "dsdd",
      name: 'Electrical Conference',
      description: 'More details will be available on the given url website',
      url: "https://facebook.com",
      department: 'Electrical',
      faculty: 'Engineering',
      startDate: DateTime.now(),
      endDate: DateTime.now(),
      online: true),EventModel(
      id: "dsdd",
      name: 'Electrical Conference',
      description: 'More details will be available on the given url website',
      url: "https://facebook.com",
      department: 'Electrical',
      faculty: 'Engineering',
      startDate: DateTime.now(),
      endDate: DateTime.now(),
      online: true),
];
